name: Generate MO
on:
  push:
    branches: [ master ]
    paths:
    - '**.po'
permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs: 
  run:
    
    name: Generate mo
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
    - name: Setup Perl environment
      # You may pin to the exact commit or the version.
      # uses: shogo82148/actions-setup-perl@8d2e3d59a9516b785ed32169d48a4888eaa9b514
      uses: shogo82148/actions-setup-perl@98dfedee230bcf1ee68d5b021931fc8d63f2016e
    - name: msgfmt
      # You may pin to the exact commit or the version.
      # uses: whtsky/msgfmt-action@6b2181f051b002182d01a1e1f1aff216230c5a4d
      uses: whtsky/msgfmt-action@6b2181f051b002182d01a1e1f1aff216230c5a4d
    - name: Generate mo
      run:  perl tools/update_mo.pl;

    - name: Commit changes
      uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5
      with:
       
        message: "Generate mo"
    - name: Push changes
 
      uses: actions-go/push@7ad7ce209f2a038e7bca929b7a4c92026363f856
  
